### ISSUE TITLE
Different heights for window and door-window

### ISSUE THREAD

**Issue by skydado** [samoswall/pic-shutter-card#2]
Hi @samoswall, thanks for your nice work!

Not really an issue, but probably an improvement.
I have windows and door-windows (so they have different heights) and I'd like to show them in an horizontal stack.
I've tried with layout-card and card-mod but the result is awful because the full card is squeezed including buttons and text.
Is it a native way to have shutters with different heights in the same horizotal stack?

Can you also put the English readme as default pls?

**Comment by samoswall** [comment]
I will think about how to do this, but so far I see problems:
- if there are 2 curtains in one card, they must be moved separately under the background of the window and there is a difficulty with processing two curtains in one card;
- if on different cards, then it is necessary to increase the height of the card, while the other card will be of a small height.

**Comment by skydado** [comment]
Maybe I explained it badly.
Not aiming to have a single card with both window and door-window.
Just want to define the image height without impacting buttons, title, text. So that, if I place 2 cards close each other, they look similar a part from the image height.

**Comment by samoswall** [comment]
Hi @skydado 
Do you want something similar?
![ScreenRecorderProject5](https://github.com/samoswall/pic-shutter-card/assets/80251553/fc25ec55-f0f7-40c3-82ed-5369f122e10f)

**Comment by skydado** [comment]
That is perfect!! ❤️

**Comment by samoswall** [comment]
> That is perfect!! ❤️

OK, I'll release an update tonight.

**Comment by samoswall** [comment]
Added support in version 1.2.1
