### ISSUE TITLE
Animation Issue and Offset

### ISSUE THREAD

**Issue by aigle1234** [samoswall/pic-shutter-card#3]
Hello,

Thank you for this kind project and all those customizations !
I have an issue with the animation which it doesn't seem to work.

I have tested with this sample code:
```
type: custom:pic-shutter-card
entities:
  - entity: cover.volet_xxxx
    shutter_animation: show
```
Web browser : Chrome & Edge
Home Assistant Core : 2024.5.1

Is-there something wrong on my side ?

**Comment by samoswall** [comment]
Microsoft Edge Версия 124.0.2478.80 (Официальная сборка) (64-разрядная версия)
FireFox Browser 125.0.3 (64-разрядный)
Yandex Browser Версия 24.4.2.887 (64-bit)
Chrome Version 124.0.6367.119 (Official Build) (64-bit)

Everything works in these browsers!
Home Assistant:
Core 2024.5.1
Supervisor 2024.04.4
Operating System 12.2
Пользовательский интерфейс 20240501.0

**Comment by aigle1234** [comment]
Ok let's see
Thank you for your very fast feeback !

In addition, would you think it could be possible to add an offset parameter to match the real position of the cover ?

**Comment by samoswall** [comment]
offset parameter - Which?

**Comment by aigle1234** [comment]
When I set the cover entity to 50% for example in home assistant, my expectation would be that the cover goes down half way. However when setting a cover to 50% its more like 80% closed because once the shutter touches the ground the motor continues running until all the slits are closed completely.
With the offset, that 50% in the app is actually half way down the window and not 50% through the runtime of the motor powering the blinds.

**Comment by samoswall** [comment]
Decrease the value `shutter_max_position` int (px)
shutter_min_position + shutter_max_position = 131 px (default) = 100% height (height in pixels)

**Comment by aigle1234** [comment]
It's working for middle-low position but the issue is now when it's full opened, the picture window is not full opened:
That's why I'm thinking about an "offset".

![image](https://github.com/samoswall/pic-shutter-card/assets/48964174/3c4b0385-62b5-4dd7-b425-8eb1a1c49fcd)

![image](https://github.com/samoswall/pic-shutter-card/assets/48964174/46db12c9-3527-4ff6-abfb-cb1a30185c50)

```
type: custom:pic-shutter-card
entities:
  - entity: cover.volet_musique
    shutter_animation: show
    shutter_max_position: 107
    shutter_min_position: 24
```

**Comment by samoswall** [comment]
![Скриншот 05 05 24_20 00 09](https://github.com/samoswall/pic-shutter-card/assets/80251553/f6601128-5afc-4308-80a8-2fe112003e3c)

**Comment by samoswall** [comment]
![Скриншот 05 05 24_20 04 50](https://github.com/samoswall/pic-shutter-card/assets/80251553/cbf709ae-1a1b-418a-84af-87d762b4b785)

**Comment by aigle1234** [comment]
Unfortunately, I don't see how to play with `shutter_max_position ` / `shutter_min_position ` / `shutter_top` and solve this issue (the shutter touches the ground the motor continues running until all the slits are closed completely).

The goal will be to have an new parameter "offset" (int) to change the behavior:
current behavior : % (picture position) <-> % (cover.entity position)
target behavior : **% (picture position) <-> % (cover.entity position + offset)**

Here is the logic for the Offset and picture update calcul:
-if % (cover.entity) < offset <-> % (picture position) = 0
-if % (cover.entity) >= offset <-> % (picture position) = % ( (cover.entity) - offset) * (100 / (100 - offset)))

Example:
Offset 15
% (picture position) 0 <-> % (cover.entity) 0
% (picture position) 0 <-> % (cover.entity) 5
% (picture position) 0 <-> % (cover.entity) 10
% (picture position) 0 <-> % (cover.entity) 15
% (picture position) ((25 - 15) * (100 / (100 - 15)) = 11,8 <-> % (cover.entity) 25
% (picture position) ((100 - 15) * (100 / (100 - 15)) = 100 <-> % (cover.entity) 100

**Comment by samoswall** [comment]
There is a `shutter_min_position` for this.
Reduce it by 15

**Comment by aigle1234** [comment]
> There is a `shutter_min_position` for this. Reduce it by 15

If I use `shutter_min_position`, I will find this min position on the picture when the cover is fully opened, the goal is to have the picture also fully opened.

**Comment by samoswall** [comment]
If the value of the current_position attribute of the cover entity changes from 0 to 100, then the position of the curtain image is displayed from shutter_min_position to shutter_max_position.
Negative values can be used for shutter_min_position and shutter_top.

**Comment by aigle1234** [comment]
Ok thank you for all these feebdack
which value would you use as `shutter_min_position`  `shutter_max_position` `shutter_top` in case of offset of 15 to test please ?

**Comment by samoswall** [comment]
Try clearing the browser cache
Code
```yaml
type: custom:pic-shutter-card
entities:
- entity: cover.roll_1
```
equal to
```yaml
type: custom:pic-shutter-card
entities:
- entity: cover.roll_1
  shutter_min_position: 4
  shutter_max_position: 127
  shutter_top: 17
```
for this image
![Скриншот 05 05 24_22 47 27](https://github.com/samoswall/pic-shutter-card/assets/80251553/eabaccb1-d361-41e5-85c2-0d019cb548b5)

**Comment by samoswall** [comment]
decreasing the shutter_top will raise the curtain up by the desired pixel value
shutter_min_position - creates the appearance of a curtain, for beauty, it can be made equal to 1
in other cases, when the curtain cannot be fully raised up, this value is increased

**Comment by aigle1234** [comment]
I agree, but how can I change the settings for the picture takes into account my offset ?
For example: I need that 65% of my cover equals to the picture on the right which represents the real position of my cover ?
![image](https://github.com/samoswall/pic-shutter-card/assets/48964174/69566eec-0735-418e-b76e-1fd419af6dcd)
For me the algorithm of the picture should be for offset of 15 for example:
(picture position) 0% <-> (cover.entity) 0%
(picture position) 0% <-> (cover.entity) 5%
(picture position) 0% <-> (cover.entity) 10%
(picture position) 0% <-> (cover.entity) 15%
(picture position) ((25 - 15) * (100 / (100 - 15)) = 11,8% <-> (cover.entity) 25%
etc....
% (picture position) ((100 - 15) * (100 / (100 - 15)) = 100% <-> (cover.entity) 100

**Comment by samoswall** [comment]
I don't understand your problem.
You have everything displayed correctly!
![Скриншот 06 05 24_01 29 12](https://github.com/samoswall/pic-shutter-card/assets/80251553/a56c3273-4681-4a92-9b3e-41c7c6e4f2af)
If you have an inverse percentage display, then use
```yaml
invert_percentage: true
```

**Comment by samoswall** [comment]
![Скриншот 06 05 24_01 42 00](https://github.com/samoswall/pic-shutter-card/assets/80251553/75ef1a00-33d6-414a-a84b-75eedfef1ef1)

**Comment by aigle1234** [comment]
Hello,
Sorry pictures were not cleared enough, and maybe my explanations too.
I have just found another guy who had the exactly same issue and has developped a fix to add the offset feature.
Here are links:
[Offset Explanation](https://github.com/MaxWinterstein/hass-shutter-card?tab=readme-ov-file#offset-configuration)
[Fix code](https://github.com/MaxWinterstein/hass-shutter-card/commit/5ce64131e93dbde03f4d7ad53ec8a0acdbb9fde5#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

I have quickly tested to inject on your current js file and it seems to work.

The only remains feature to be perfect will be to find a workaround to fix 'set the shutter to real 0% when 
when we have reached the remaining offset':

![image](https://github.com/samoswall/pic-shutter-card/assets/48964174/0a8a0017-47cb-4558-bef8-ada9a5d3c6d4)

**Comment by samoswall** [comment]
Hi!
Finally, I understand you! :))    (Maybe it's a language barrier)
It is possible to set the offset from above - this is min_position.
You want to make an offset from the bottom.
When the curtain goes down by 85% (15% remains open), you need to display 100% closed on the card (the value of open is 0%).
I understand correctly that: the value of the current_position attribute of the cover entity changes from from 100 to 15 for your case?

**Comment by samoswall** [comment]
I will add a bottom offset setting, but I need time to check how it will affect other functions.

**Comment by aigle1234** [comment]
Hello,

> When the curtain goes down by 85% (15% remains open)

 -> Yes, curtain is on the ground but has not still finished (15% left)

> you need to display 100% closed on the card

-> Yes, we can consider the card 100% closed

With the fix code link:
=> card is OK
=> if we slide down to the bottom of the card, 100% closed is displayed on the card but there is still 15% missing on the curtain to be fully closed.
![image](https://github.com/samoswall/pic-shutter-card/assets/48964174/de3b5f42-91de-4ecc-bdba-ef23262fc089)
![image](https://github.com/samoswall/pic-shutter-card/assets/48964174/cdda510e-81f5-4443-acad-c98a4a667e71)

**Comment by samoswall** [comment]
Added support in version v.1.2.2

**Comment by aigle1234** [comment]
Hi,
wonderful thank you !!!
Is-it possible to have `not_show` option for `title_position` ?
