### ISSUE TITLE
Great job

### ISSUE THREAD

**Issue by sdeodom** [samoswall/pic-shutter-card#4]
Very good work

Thank you for your work, is it possible to disable the up button when the shutter is up and deactivate the down button when the shutter is down, and have 'is closed' when the shutter is closed instead of 0% and 'is open' when the shutter is open instead of 100%.
thank you very much for your work

**Comment by samoswall** [comment]
Since you have suggested an improvement, I will ask for your opinion.
Replacing 0% and 100% with "closed" and "open" is not difficult, but can it be done using the card settings?
For example:
replace_0: "closed"
replace_100: "open" 
This will allow you to use a multilingual view and flexible user settings (open can be replaced with: top, raised, pushed back and ...)

**Comment by sdeodom** [comment]
Thank you for this quick response, I completely agree with your opinion, the result will be more flexible. Congratulations again for your work. Sorry for my English, I'm only a little French.

**Comment by samoswall** [comment]
Implemented in version 1.2.3

**Comment by samoswall** [comment]
Implemented in version 1.2.3

**Comment by sdeodom** [comment]
Thank you very much, it's super great, it works perfectly, to complete the application, it would be great to add the same thing for a sliding gate and a two-leaf gate.
I'm sorry not to at least offer you a coffee, but transactions with Russia are very complicated.
Many thanks again

**Comment by samoswall** [comment]
> Thank you very much, it's super great, it works perfectly, to complete the application, it would be great to add the same thing for a sliding gate and a two-leaf gate. I'm sorry not to at least offer you a coffee, but transactions with Russia are very complicated. Many thanks again

Sliding gate and a two-leaf gate you can do it with your own pictures.
Example:
![vorota](https://github.com/user-attachments/assets/6bcf7757-c3c1-491f-be7c-fd31384392a4)
